triggers:
  - name: triggertest1
    type: trigger
    source:
      message: 'the of the rdfffdsniffc'
      
  - name: triggertest2
    type: trigger
    source:
      message: 'tesRRtfggfifhhdffdfnigg of syggffgggggns2'
      counter: 1
      
  - name: triggertest3
    type: trigger
    source:
      message: 'testfFthrfTffffddhggniRggRnfyhthygfg of ssyyjnc3'
      counter: 2
