jobs:
  - name: script-p11
    type: runSh
    #serial: true
    steps:
      - GET: sample-script1
      - GET: triggertest1
      - TASK:
        - script: pwd
        - script: ./GET/sample-script/sample-script/echo.sh
  - name: script-p2
    type: runSh
    #serial: true
    steps:
      - GET: sample-script1
      - GET: triggertest2
      - TASK:
        - script: ls
        - script: ./GET/sample-script/sample-script/echo.sh
  - name: script-p3
    type: runSh
    #serial: true
    steps:
      - GET: sample-script1
      - GET: triggertest3
      - TASK:
        - script: ps
        - script: ./GET/sample-script/sample-script/echo.sh


