triggers:
  - name: triggertest1
    type: trigger
    source:
      message: 'tesehytinwglthtbth12 triifgfuggujythre in yml oekke13ewuh5'
      
  - name: triggertest2
    type: trigger
    source:
      message: 'twoeeth1wewyyhhrrgg3tibeh5'
      counter: 1
      
  - name: triggertest3
    type: trigger
    source:
      message: 'coneteewthe thekryyrrinfffyeewwggthry3hbi5'
      counter: 1
