triggers:
  - name: triggertest14
    type: trigger
    source:
      message: 'the tffefTHggghRgffstgithyndg of the rysnc'
      
  - name: triggertest12
    type: trigger
    source:
      message: 'tesRRtfggfifhhfng of sygggggggns2'
      counter: 1
      
  - name: triggertest13
    type: trigger
    source:
      message: 'testfFthrfTffhgniRggRnyhthygfg of ssyyjnc3'
      counter: 2
