triggers:
  - name: triggertest1
    type: trigger
    source:
      message: 'the testing of the rync'
      
  - name: triggertest2
    type: trigger
    source:
      message: 'testing of syn2'
      counter: 1
      
  - name: triggertest3
    type: trigger
    source:
      message: 'testing of sync3'
      counter: 1
