triggers:
  - name: triggertest143
    type: trigger
    source:
      message: 'testing12 trigger in yml14thy'
      
  - name: triggertest234
    type: trigger
    source:
      message: 'thetynewthynew'
      counter: 1
      
  - name: triggertest3
    type: trigger
    source:
      message: 'conternew'
      counter: 1
