triggers:
  - name: triggertest1
    type: trigger
    source:
      message: 'testing12 triggere in yml one13u5'
      
  - name: triggertest2
    type: trigger
    source:
      message: 'twoe13t5'
      counter: 1
      
  - name: triggertest3
    type: trigger
    source:
      message: 'conternewthry3i5'
      counter: 1
