triggers:
  - name: triggertest1
    type: trigger
    source:
      message: 'tesetinwgthtbth12 triifgfuggujythre in yml oene13ewuh5'
      
  - name: triggertest2
    type: trigger
    source:
      message: 'twoeeth1wewhhrrgg3tibeh5'
      counter: 1
      
  - name: triggertest3
    type: trigger
    source:
      message: 'coneteewthe thekrrrinyeewwggthry3hbi5'
      counter: 1
