triggers:
  - name: triggertest1
    type: trigger
    source:
      message: 'the of the rddsniffc'
      
  - name: triggertest2
    type: trigger
    source:
      message: 'tesRRtfggfifhhddfnigg of syggffgggggns2'
      counter: 1
      
  - name: triggertest3
    type: trigger
    source:
      message: 'testfFthrfTffddhggniRggRnfyhthygfg of ssyyjnc3'
      counter: 2
