triggers:
  - name: triggertest3p
    type: trigger
    version::
      message: 'npooppwe8'
      
  #- name: triggertest2
  #  type: trigger
  #  source:
   #   message: 'new teswt2'
    #  counter: 1
      
  #- name: triggertest3
   # type: trigger
  #  source:
   #   message: 'tewwt3'
    #  counter: 3
