jobs:
  - name: script-newtestnode123NEW
    type: runSh
    serial: true
    steps:
      - GET: sample-script1
      - TASK:
        - script: pwd
        - script: ls
        - script: ./GET/sample-script1/sample-script1/echo.sh
 
