triggers:
  - name: triggertest1
    type: trigger
    source:
      message: 'testing12 trigger in yml14thyrthntg'
      
  - name: triggertest2
    type: trigger
    source:
      message: 'thetynewthynewthydg'
      counter: 1
      
  - name: triggertest3
    type: trigger
    source:
      message: 'conternew'
      counter: 1
