triggers:
  - name: triggertest14
    type: trigger
    source:
      message: 'the tffefTHRgffstindg of the rysnc'
      
  - name: triggertest12
    type: trigger
    source:
      message: 'tesRRtfggfiffng of sygggggggns2'
      counter: 1
      
  - name: triggertest13
    type: trigger
    source:
      message: 'testfFthrfThniRggRnyhthygfg of ssyyjnc3'
      counter: 2
