triggers:
  - name: triggertest14
    type: trigger
    source:
      message: 'the of the rysnffc'
      
  - name: triggertest12
    type: trigger
    source:
      message: 'tesRRtfggfifhhfngg of syggffgggggns2'
      counter: 1
      
  - name: triggertest13
    type: trigger
    source:
      message: 'testfFthrfTffhgniRggRnfyhthygfg of ssyyjnc3'
      counter: 2
