triggers:
  - name: triggertest1
    type: trigger
    source:
      message: 'the of test1'
      
  - name: triggertest2
    type: trigger
    source:
      message: 'new test2'
      counter: 1
      
  - name: triggertest3
    type: trigger
    source:
      message: 'test3'
      counter: 2
