jobs:
  - name: script-newtest2
    type: runSh
    steps:
      - GET: sample-script1
      - TASK:
        - script: ps
        - script: ls
        - script: ./GET/sample-script1/sample-script1/echo.sh
 
  - name: gittest1
    type: manifest
    steps:
      - GET: newgitres
