triggers:
  - name: triggertest1
    type: trigger
    source:
      message: 'testing12 triggere in yml one1'
      
  - name: triggertest2
    type: trigger
    source:
      message: 'twoe1'
      counter: 1
      
  - name: triggertest3
    type: trigger
    source:
      message: 'conternew'
      counter: 1
