jobs:
  - name: ecstest6
    type: manifest
    steps:
      - GET: new-image
      - GET: new-image123
      - GET: triggertest13
      
  - name: ecstest665
    type: manifest
    steps:
      - GET: new-image
      - GET: new-image123
      - GET: triggertest14

