triggers:
  - name: triggertest1
    type: trigger
    source:
      message: 'tesetingb12 triggere in yml oene13wuh5'
      
  - name: triggertest2
    type: trigger
    source:
      message: 'twoee1ew3tbh5'
      counter: 1
      
  - name: triggertest3
    type: trigger
    source:
      message: 'coneteernewwthry3hbi5'
      counter: 1
