jobs:
  - name: script-newtest1
    type: runSh
    steps:
      - GET: sample-script
      - TASK:
        - script: ps
        - script: ls
        - script: ./GET/sample-script/sample-script/echo.sh
 
  - name: gittest1
    type: manifest
    steps:
      - GET: newgitres
