triggers:
  - name: triggertest14
    type: trigger
    source:
      message: 'the tffefTHffgggghRgffstgithyndg of the rysnc'
      
  - name: triggertest12
    type: trigger
    source:
      message: 'tesRRtfggfifhhfngg of sygggggggns2'
      counter: 1
      
  - name: triggertest13
    type: trigger
    source:
      message: 'testfFthrfTffhgniRggRnyhthygfg of ssyyjnc3'
      counter: 2
