triggers:
  - name: triggertest14
    type: trigger
    source:
      message: 'the tffefTHRgffstindg of the rysnc'
      
  - name: triggertest12
    type: trigger
    source:
      message: 'tesRRtffiffng of syns2'
      counter: 1
      
  - name: triggertest13
    type: trigger
    source:
      message: 'testfFthrfThniRRnyhthygfg of ssyyjnc3'
      counter: 2
