triggers:
  - name: triggertest1
    type: trigger
    source:
      message: 'testing12 triggere in yml one13u'
      
  - name: triggertest2
    type: trigger
    source:
      message: 'twoe13t'
      counter: 1
      
  - name: triggertest3
    type: trigger
    source:
      message: 'conternewthry3i'
      counter: 1
