triggers:
  - name: triggertest1
    type: trigger
    source:
      message: 'tesetingbth12 triiuggere in yml oene13ewuh5'
      
  - name: triggertest2
    type: trigger
    source:
      message: 'twoee1ewgg3tibeh5'
      counter: 1
      
  - name: triggertest3
    type: trigger
    source:
      message: 'coneteerineewwggthry3hbi5'
      counter: 1
