triggers:
  - name: triggertest1
    type: trigger
    source:
      message: 'tesetingthtbth12 triiuggere in yml oene13ewuh5'
      
  - name: triggertest2
    type: trigger
    source:
      message: 'twoeeth1ewhhrrgg3tibeh5'
      counter: 1
      
  - name: triggertest3
    type: trigger
    source:
      message: 'conetethekrrrinyeewwggthry3hbi5'
      counter: 1
