triggers:
  - name: triggertest1
    type: trigger
    source:
      message: 'tesetingb12 triggere in yml one13wuh5'
      
  - name: triggertest2
    type: trigger
    source:
      message: 'twoe1ew3tbh5'
      counter: 1
      
  - name: triggertest3
    type: trigger
    source:
      message: 'coneternewwthry3hbi5'
      counter: 1
