triggers:
  # - name: t111
     type: trigger
     version:
       counter: 71
   #- name: trigger1
     type: trigger
     version:
    #  message: 'new teswt2'
       counter: 1
      
  #- name: triggertest3
   # type: trigger
  #  source:
   #   message: 'tewwt3'
    #  counter: 3
