triggers:
  - name: triggertest1
    type: trigger
    source:
      message: 'the tefgffstindg of the rysnc'
      
  - name: triggertest2
    type: trigger
    source:
      message: 'testiffng of syns2'
      counter: 1
      
  - name: triggertest3
    type: trigger
    source:
      message: 'testfing of ssync3'
      counter: 1
