triggers:
  - name: triggertest1
    type: trigger
    source:
      message: 'tesetingb12 triiggere in yml oene13ewuh5'
      
  - name: triggertest2
    type: trigger
    source:
      message: 'twoee1ew3tibeh5'
      counter: 1
      
  - name: triggertest3
    type: trigger
    source:
      message: 'coneteerineewwthry3hbi5'
      counter: 1
