triggers:
  - name: triggertest1
    type: trigger
    source:
      message: 'the tefTHRgffstindg of the rysnc'
      
  - name: triggertest2
    type: trigger
    source:
      message: 'tesRRtiffng of syns2'
      counter: 1
      
  - name: triggertest3
    type: trigger
    source:
      message: 'testfFTiRRng of ssync3'
      counter: 1
