triggers:
  - name: triggertest1
    type: trigger
    source:
      message: 'the of the rdthtfffdsniffc'
      
  - name: triggertest2
    type: trigger
    source:
      message: 'tesRRtfggfifhhdttffdfnigg of syggffgggggns2'
      counter: 1
      
  - name: triggertest3
    type: trigger
    source:
      message: 'testfFthrfTffffddhtggniRggRnfyhthygfg of ssyyjnc3'
      counter: 2
