triggers:
  - name: triggertest1
    type: trigger
    source:
      message: 'testing12 triggere in yml one13'
      
  - name: triggertest2
    type: trigger
    source:
      message: 'twoe13'
      counter: 1
      
  - name: triggertest3
    type: trigger
    source:
      message: 'conternewthry3'
      counter: 1
