triggers:
  - name: triggertest1
    type: trigger
    source:
      message: 'the teffsting of the rync'
      
  - name: triggertest2
    type: trigger
    source:
      message: 'testiffng of syn2'
      counter: 1
      
  - name: triggertest3
    type: trigger
    source:
      message: 'testfing of sync3'
      counter: 1
