triggers:
  - name: triggertest1
    type: trigger
    source:
      message: 'testing12 trigger in yml14'
      
  - name: triggertest2
    type: trigger
    source:
      message: 'thetyr'
      counter: 1
      
  - name: triggertest3
    type: trigger
    source:
      message: 'conter'
      counter: 1
