triggers:
  - name: triggertest1
    type: trigger
    source:
      message: 'testing12 triggere in yml one13uh5'
      
  - name: triggertest2
    type: trigger
    source:
      message: 'twoe13th5'
      counter: 1
      
  - name: triggertest3
    type: trigger
    source:
      message: 'conternewthry3hi5'
      counter: 1
